name: checks

on: [ push, pull_request, workflow_dispatch]

jobs:

  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: coursier/setup-action@v1
      with:
        jvm: zulu:21.0.2

    - name: Test
      run: sbt test

