name: checks

on: [ push, pull_request, workflow_dispatch]

jobs:

  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: olafurpg/setup-scala@v14
      with:
        java-version: openjdk@1.21.0-2

    - name: Test
      run: sbt test

